### ISSUE TITLE
Interest for pre-orders

### ISSUE THREAD

**Issue by ole-tange** [robertfisk/USG#5]
Add your email address here if you are interested in pre-ordering next batch.

Ole Tange <github-usg@tange.dk>

**Comment by robertfisk** [comment]
Alternatively, if you don't want to leave your address here in public you can contact me directly: <globotron@fastmail.com>

**Comment by robertfisk** [comment]
The online store is now open for business!

[https://globotron.nz/](https://globotron.nz/)
